### ISSUE TITLE
White operators on white background

### ISSUE THREAD

**Issue by andrsd** [dschwen/language-moose#1]
When using Atom with light themes, operators are rendered in white thus making them invisible.
`.keyword.operator.moose` has to somehow inherit the theme color.

**Comment by dschwen** [comment]
Oh right. It didn't occur to me that anyone would use a light theme when
coding ;-)

**Comment by andrsd** [comment]
I was coding at a very bright location yesterday (outside of work) and the dark theme was unusable, so I tried the light one and noticed that all my operators were "gone" ;-)

**Comment by dschwen** [comment]
I'll look into it. I'm currently on travel though.

**Comment by dschwen** [comment]
Fixed in 2951b04, published as v0.16.0
