### ISSUE TITLE
Executable from combined module not found

### ISSUE THREAD

**Issue by aeslaughter** [dschwen/language-moose#3]
Run make in `~/projects/moose/modules` and then edit an input file on a module and you get lots of errors about an executable not being found.

**Comment by dschwen** [comment]
Well, the executable is parked under `modules/combined`. This means it is not in a parent directory of any of the other module directories. How does peacock handle this? IMO it does not make much sense. The combined executable should just be directly under `modules`.

**Comment by aeslaughter** [comment]
I don't know if peacock handles this, haven't tried. I can agree that the executable should be in modules dir, but you will need to complain to @permcody about that.

**Comment by dschwen** [comment]
A quick fix would be to drop a symlink into `modules` that points to `modules/combined/modules-opt`!
