### ISSUE TITLE
no moose application executable found

### ISSUE THREAD

**Issue by CDmaterial** [dschwen/language-moose#9]
Atom version: 1.42.0
This error is similar to the question raised from this link: [https://groups.google.com/forum/#!topic/moose-users/bVybTo8UBfc]
I tried reinstall Atom, and it works for a few minutes and then this problem happen again.

**Comment by dschwen** [comment]
Atom has been sunsetted and we've moved on to VSCode: https://marketplace.visualstudio.com/items?itemName=DanielSchwen.moose-language-support
